In [12]:
import requests

In [15]:
## 공공데이터포털에서 제공하는 주소 값을 변수에 대입
url = 'http://apis.data.go.kr/1741000/RegistrationPopulationByRegion/getRegistrationPopulationByRegion'

# 서비스키를 변수에 대입
service_key = 'dtbWOdJ/Cz5HE0DGLU+CRPe7pOW0NIQBUcGEqsHZaTRiYCI/5+zugwzQjcvuId7NPdg6rUiW+ft3fm7yqyD4pw=='

# 해당하는 api에서 요청하는 변수들을 지정
_param = {
    'ServiceKey' : service_key,
    'pageNo' : 1,
    'numOfRows' : 50
}

In [16]:
## api에 요청을 보낸다.
## 특정 주소에 요청 -> 해당하는 서버에서 메시지를 보내준다.
reponse = requests.get(url, params = _param, verify = False)

In [18]:
print(reponse.content)

b'<?xml version="1.0" encoding="UTF-8"?>\n\n<RegistrationPopulationByRegion>\n  <head>\n    <totalCount>266</totalCount>\n    <numOfRows>50</numOfRows>\n    <pageNo>1</pageNo>\n    <type>XML</type>\n    <RESULT>\n      <resultCode>INFO-0</resultCode>\n      <resultMsg>NOMAL SERVICE</resultMsg>\n    </RESULT>\n  </head>\n  <row>\n    <wrttimeid>2008</wrttimeid>\n    <seq>1</seq>\n    <regi>\xea\xb3\x84</regi>\n    <population_tot>49540367</population_tot>\n    <population_man>24822897</population_man>\n    <population_female>24717470</population_female>\n    <houshol>19005339</houshol>\n  </row>\n  <row>\n    <wrttimeid>2008</wrttimeid>\n    <seq>2</seq>\n    <regi>\xec\x84\x9c\xec\x9a\xb8</regi>\n    <population_tot>10200827</population_tot>\n    <population_man>5061809</population_man>\n    <population_female>5139018</population_female>\n    <houshol>4097562</houshol>\n  </row>\n  <row>\n    <wrttimeid>2008</wrttimeid>\n    <seq>3</seq>\n    <regi>\xeb\xb6\x80\xec\x82\xb0</regi>\n    <population_tot>3564577</population_tot>\n    <population_man>1773154</population_man>\n    <population_female>1791423</population_female>\n    <houshol>1311724</houshol>\n  </row>\n  <row>\n    <wrttimeid>2008</wrttimeid>\n    <seq>4</seq>\n    <regi>\xeb\x8c\x80\xea\xb5\xac</regi>\n    <population_tot>2492724</population_tot>\n    <population_man>1246873</population_man>\n    <population_female>1245851</population_female>\n    <houshol>894969</houshol>\n  </row>\n  <row>\n    <wrttimeid>2008</wrttimeid>\n    <seq>5</seq>\n    <regi>\xec\x9d\xb8\xec\xb2\x9c</regi>\n    <population_tot>2692696</population_tot>\n    <population_man>1356473</population_man>\n    <population_female>1336223</population_female>\n    <houshol>1014755</houshol>\n  </row>\n  <row>\n    <wrttimeid>2008</wrttimeid>\n    <seq>6</seq>\n    <regi>\xea\xb4\x91\xec\xa3\xbc</regi>\n    <population_tot>1422702</population_tot>\n    <population_man>705817</population_man>\n    <population_female>716885</population_female>\n    <houshol>513021</houshol>\n  </row>\n  <row>\n    <wrttimeid>2008</wrttimeid>\n    <seq>7</seq>\n    <regi>\xeb\x8c\x80\xec\xa0\x84</regi>\n    <population_tot>1480895</population_tot>\n    <population_man>741611</population_man>\n    <population_female>739284</population_female>\n    <houshol>531682</houshol>\n  </row>\n  <row>\n    <wrttimeid>2008</wrttimeid>\n    <seq>8</seq>\n    <regi>\xec\x9a\xb8\xec\x82\xb0</regi>\n    <population_tot>1112407</population_tot>\n    <population_man>572815</population_man>\n    <population_female>539592</population_female>\n    <houshol>389735</houshol>\n  </row>\n  <row>\n    <wrttimeid>2008</wrttimeid>\n    <seq>9</seq>\n    <regi>\xea\xb2\xbd\xea\xb8\xb0</regi>\n    <population_tot>11292264</population_tot>\n    <population_man>5690673</population_man>\n    <population_female>5601591</population_female>\n    <houshol>4284475</houshol>\n  </row>\n  <row>\n    <wrttimeid>2008</wrttimeid>\n    <seq>10</seq>\n    <regi>\xea\xb0\x95\xec\x9b\x90</regi>\n    <population_tot>1508575</population_tot>\n    <population_man>759282</population_man>\n    <population_female>749293</population_female>\n    <houshol>606950</houshol>\n  </row>\n  <row>\n    <wrttimeid>2008</wrttimeid>\n    <seq>11</seq>\n    <regi>\xec\xb6\xa9\xeb\xb6\x81</regi>\n    <population_tot>1519587</population_tot>\n    <population_man>765398</population_man>\n    <population_female>754189</population_female>\n    <houshol>587411</houshol>\n  </row>\n  <row>\n    <wrttimeid>2008</wrttimeid>\n    <seq>12</seq>\n    <regi>\xec\xb6\xa9\xeb\x82\xa8</regi>\n    <population_tot>2018537</population_tot>\n    <population_man>1020317</population_man>\n    <population_female>998220</population_female>\n    <houshol>812871</houshol>\n  </row>\n  <row>\n    <wrttimeid>2008</wrttimeid>\n    <seq>13</seq>\n    <regi>\xec\xa0\x84\xeb\xb6\x81</regi>\n    <population_tot>1855772</population_tot>\n    <population_man>924770</population_man>\n    <population_female>931002</population_female>\n    <houshol>710550</houshol>\n  </row>\n  <row>\n    <wrttimeid>2008</wrttimeid>\n    <seq>14</seq>\n    <regi>\xec\xa0\x84\xeb\x82\xa8</regi>\n    <population_tot>1919000</population_tot>\n    <population_man>958491</population_man>\n    <population_female>960509</population_female>\n    <houshol>773087</houshol>\n  </row>\n  <row>\n    <wrttimeid>2008</wrttimeid>\n    <seq>15</seq>\n    <regi>\xea\xb2\xbd\xeb\xb6\x81</regi>\n    <population_tot>2673931</population_tot>\n    <population_man>1343199</population_man>\n    <population_female>1330732</population_female>\n    <houshol>1058099</houshol>\n  </row>\n  <row>\n    <wrttimeid>2008</wrttimeid>\n    <seq>16</seq>\n    <regi>\xea\xb2\xbd\xeb\x82\xa8</regi>\n    <population_tot>3225255</population_tot>\n    <population_man>1622127</population_man>\n    <population_female>1603128</population_female>\n    <houshol>1203767</houshol>\n  </row>\n  <row>\n    <wrttimeid>2008</wrttimeid>\n    <seq>17</seq>\n    <regi>\xec\xa0\x9c\xec\xa3\xbc</regi>\n    <population_tot>560618</population_tot>\n    <population_man>280088</population_man>\n    <population_female>280530</population_female>\n    <houshol>214681</houshol>\n  </row>\n  <row>\n    <wrttimeid>2009</wrttimeid>\n    <seq>1</seq>\n    <regi>\xea\xb3\x84</regi>\n    <population_tot>49773145</population_tot>\n    <population_man>24929939</population_man>\n    <population_female>24843206</population_female>\n    <houshol>19261292</houshol>\n  </row>\n  <row>\n    <wrttimeid>2009</wrttimeid>\n    <seq>2</seq>\n    <regi>\xec\x84\x9c\xec\x9a\xb8</regi>\n    <population_tot>10208302</population_tot>\n    <population_man>5059269</population_man>\n    <population_female>5149033</population_female>\n    <houshol>4116660</houshol>\n  </row>\n  <row>\n    <wrttimeid>2009</wrttimeid>\n    <seq>3</seq>\n    <regi>\xeb\xb6\x80\xec\x82\xb0</regi>\n    <population_tot>3543030</population_tot>\n    <population_man>1761202</population_man>\n    <population_female>1781828</population_female>\n    <houshol>1323771</houshol>\n  </row>\n  <row>\n    <wrttimeid>2009</wrttimeid>\n    <seq>4</seq>\n    <regi>\xeb\x8c\x80\xea\xb5\xac</regi>\n    <population_tot>2489781</population_tot>\n    <population_man>1243878</population_man>\n    <population_female>1245903</population_female>\n    <houshol>906470</houshol>\n  </row>\n  <row>\n    <wrttimeid>2009</wrttimeid>\n    <seq>5</seq>\n    <regi>\xec\x9d\xb8\xec\xb2\x9c</regi>\n    <population_tot>2710579</population_tot>\n    <population_man>1364809</population_man>\n    <population_female>1345770</population_female>\n    <houshol>1026936</houshol>\n  </row>\n  <row>\n    <wrttimeid>2009</wrttimeid>\n    <seq>6</seq>\n    <regi>\xea\xb4\x91\xec\xa3\xbc</regi>\n    <population_tot>1433640</population_tot>\n    <population_man>711091</population_man>\n    <population_female>722549</population_female>\n    <houshol>524093</houshol>\n  </row>\n  <row>\n    <wrttimeid>2009</wrttimeid>\n    <seq>7</seq>\n    <regi>\xeb\x8c\x80\xec\xa0\x84</regi>\n    <population_tot>1484180</population_tot>\n    <population_man>743121</population_man>\n    <population_female>741059</population_female>\n    <houshol>538100</houshol>\n  </row>\n  <row>\n    <wrttimeid>2009</wrttimeid>\n    <seq>8</seq>\n    <regi>\xec\x9a\xb8\xec\x82\xb0</regi>\n    <population_tot>1114866</population_tot>\n    <population_man>573607</population_man>\n    <population_female>541259</population_female>\n    <houshol>394364</houshol>\n  </row>\n  <row>\n    <wrttimeid>2009</wrttimeid>\n    <seq>9</seq>\n    <regi>\xea\xb2\xbd\xea\xb8\xb0</regi>\n    <population_tot>11460610</population_tot>\n    <population_man>5773569</population_man>\n    <population_female>5687041</population_female>\n    <houshol>4359467</houshol>\n  </row>\n  <row>\n    <wrttimeid>2009</wrttimeid>\n    <seq>10</seq>\n    <regi>\xea\xb0\x95\xec\x9b\x90</regi>\n    <population_tot>1512870</population_tot>\n    <population_man>761270</population_man>\n    <population_female>751600</population_female>\n    <houshol>617693</houshol>\n  </row>\n  <row>\n    <wrttimeid>2009</wrttimeid>\n    <seq>11</seq>\n    <regi>\xec\xb6\xa9\xeb\xb6\x81</regi>\n    <population_tot>1527478</population_tot>\n    <population_man>769968</population_man>\n    <population_female>757510</population_female>\n    <houshol>599204</houshol>\n  </row>\n  <row>\n    <wrttimeid>2009</wrttimeid>\n    <seq>12</seq>\n    <regi>\xec\xb6\xa9\xeb\x82\xa8</regi>\n    <population_tot>2037582</population_tot>\n    <population_man>1029725</population_man>\n    <population_female>1007857</population_female>\n    <houshol>827846</houshol>\n  </row>\n  <row>\n    <wrttimeid>2009</wrttimeid>\n    <seq>13</seq>\n    <regi>\xec\xa0\x84\xeb\xb6\x81</regi>\n    <population_tot>1854508</population_tot>\n    <population_man>924480</population_man>\n    <population_female>930028</population_female>\n    <houshol>720993</houshol>\n  </row>\n  <row>\n    <wrttimeid>2009</wrttimeid>\n    <seq>14</seq>\n    <regi>\xec\xa0\x84\xeb\x82\xa8</regi>\n    <population_tot>1913004</population_tot>\n    <population_man>955954</population_man>\n    <population_female>957050</population_female>\n    <houshol>783156</houshol>\n  </row>\n  <row>\n    <wrttimeid>2009</wrttimeid>\n    <seq>15</seq>\n    <regi>\xea\xb2\xbd\xeb\xb6\x81</regi>\n    <population_tot>2669876</population_tot>\n    <population_man>1340977</population_man>\n    <population_female>1328899</population_female>\n    <houshol>1073367</houshol>\n  </row>\n  <row>\n    <wrttimeid>2009</wrttimeid>\n    <seq>16</seq>\n    <regi>\xea\xb2\xbd\xeb\x82\xa8</regi>\n    <population_tot>3250176</population_tot>\n    <population_man>1635700</population_man>\n    <population_female>1614476</population_female>\n    <houshol>1231461</houshol>\n  </row>\n  <row>\n    <wrttimeid>2009</wrttimeid>\n    <seq>17</seq>\n    <regi>\xec\xa0\x9c\xec\xa3\xbc</regi>\n    <population_tot>562663</population_tot>\n    <population_man>281319</population_man>\n    <population_female>281344</population_female>\n    <houshol>217711</houshol>\n  </row>\n  <row>\n    <wrttimeid>2010</wrttimeid>\n    <seq>1</seq>\n    <regi>\xea\xb3\x84</regi>\n    <population_tot>50515666</population_tot>\n    <population_man>25310385</population_man>\n    <population_female>25205281</population_female>\n    <houshol>19865179</houshol>\n  </row>\n  <row>\n    <wrttimeid>2010</wrttimeid>\n    <seq>2</seq>\n    <regi>\xec\x84\x9c\xec\x9a\xb8</regi>\n    <population_tot>10312545</population_tot>\n    <population_man>5111259</population_man>\n    <population_female>5201286</population_female>\n    <houshol>4224181</houshol>\n  </row>\n  <row>\n    <wrttimeid>2010</wrttimeid>\n    <seq>3</seq>\n    <regi>\xeb\xb6\x80\xec\x82\xb0</regi>\n    <population_tot>3567910</population_tot>\n    <population_man>1773170</population_man>\n    <population_female>1794740</population_female>\n    <houshol>1371346</houshol>\n  </row>\n  <row>\n    <wrttimeid>2010</wrttimeid>\n    <seq>4</seq>\n    <regi>\xeb\x8c\x80\xea\xb5\xac</regi>\n    <population_tot>2511676</population_tot>\n    <population_man>1255245</population_man>\n    <population_female>1256431</population_female>\n    <houshol>934598</houshol>\n  </row>\n  <row>\n    <wrttimeid>2010</wrttimeid>\n    <seq>5</seq>\n    <regi>\xec\x9d\xb8\xec\xb2\x9c</regi>\n    <population_tot>2758296</population_tot>\n    <population_man>1390356</population_man>\n    <population_female>1367940</population_female>\n    <houshol>1059664</houshol>\n  </row>\n  <row>\n    <wrttimeid>2010</wrttimeid>\n    <seq>6</seq>\n    <regi>\xea\xb4\x91\xec\xa3\xbc</regi>\n    <population_tot>1454636</population_tot>\n    <population_man>721780</population_man>\n    <population_female>732856</population_female>\n    <houshol>540875</houshol>\n  </row>\n  <row>\n    <wrttimeid>2010</wrttimeid>\n    <seq>7</seq>\n    <regi>\xeb\x8c\x80\xec\xa0\x84</regi>\n    <population_tot>1503664</population_tot>\n    <population_man>753648</population_man>\n    <population_female>750016</population_female>\n    <houshol>555768</houshol>\n  </row>\n  <row>\n    <wrttimeid>2010</wrttimeid>\n    <seq>8</seq>\n    <regi>\xec\x9a\xb8\xec\x82\xb0</regi>\n    <population_tot>1126298</population_tot>\n    <population_man>579071</population_man>\n    <population_female>547227</population_female>\n    <houshol>405501</houshol>\n  </row>\n  <row>\n    <wrttimeid>2010</wrttimeid>\n    <seq>9</seq>\n    <regi>\xea\xb2\xbd\xea\xb8\xb0</regi>\n    <population_tot>11786622</population_tot>\n    <population_man>5942454</population_man>\n    <population_female>5844168</population_female>\n    <houshol>4527282</houshol>\n  </row>\n  <row>\n    <wrttimeid>2010</wrttimeid>\n    <seq>10</seq>\n    <regi>\xea\xb0\x95\xec\x9b\x90</regi>\n    <population_tot>1529818</population_tot>\n    <population_man>769807</population_man>\n    <population_female>760011</population_female>\n    <houshol>639001</houshol>\n  </row>\n  <row>\n    <wrttimeid>2010</wrttimeid>\n    <seq>11</seq>\n    <regi>\xec\xb6\xa9\xeb\xb6\x81</regi>\n    <population_tot>1549528</population_tot>\n    <population_man>781301</population_man>\n    <population_female>768227</population_female>\n    <houshol>617431</houshol>\n  </row>\n  <row>\n    <wrttimeid>2010</wrttimeid>\n    <seq>12</seq>\n    <regi>\xec\xb6\xa9\xeb\x82\xa8</regi>\n    <population_tot>2075514</population_tot>\n    <population_man>1049363</population_man>\n    <population_female>1026151</population_female>\n    <houshol>854432</houshol>\n  </row>\n  <row>\n    <wrttimeid>2010</wrttimeid>\n    <seq>13</seq>\n    <regi>\xec\xa0\x84\xeb\xb6\x81</regi>\n    <population_tot>1868963</population_tot>\n    <population_man>931481</population_man>\n    <population_female>937482</population_female>\n    <houshol>740650</houshol>\n  </row>\n  <row>\n    <wrttimeid>2010</wrttimeid>\n    <seq>14</seq>\n    <regi>\xec\xa0\x84\xeb\x82\xa8</regi>\n    <population_tot>1918485</population_tot>\n    <population_man>958624</population_man>\n    <population_female>959861</population_female>\n    <houshol>799520</houshol>\n  </row>\n  <row>\n    <wrttimeid>2010</wrttimeid>\n    <seq>15</seq>\n    <regi>\xea\xb2\xbd\xeb\xb6\x81</regi>\n    <population_tot>2689920</population_tot>\n    <population_man>1351202</population_man>\n    <population_female>1338718</population_female>\n    <houshol>1101486</houshol>\n  </row>\n  <row>\n    <wrttimeid>2010</wrttimeid>\n    <seq>16</seq>\n    <regi>\xea\xb2\xbd\xeb\x82\xa8</regi>\n    <population_tot>3290536</population_tot>\n    <population_man>1656042</population_man>\n    <population_female>1634494</population_female>\n    <houshol>1268731</houshol>\n  </row>\n</RegistrationPopulationByRegion>\n\n'

In [19]:
# xml데이터의 형태를 dict형태로 변환해주는 라이브러리 
import xmltodict

In [20]:
# xml 데이터를 dict 형태로 변환
data = xmltodict.parse(reponse.content)

In [21]:
data

{'RegistrationPopulationByRegion': {'head': {'totalCount': '266',
   'numOfRows': '50',
   'pageNo': '1',
   'type': 'XML',
   'RESULT': {'resultCode': 'INFO-0', 'resultMsg': 'NOMAL SERVICE'}},
  'row': [{'wrttimeid': '2008',
    'seq': '1',
    'regi': '계',
    'population_tot': '49540367',
    'population_man': '24822897',
    'population_female': '24717470',
    'houshol': '19005339'},
   {'wrttimeid': '2008',
    'seq': '2',
    'regi': '서울',
    'population_tot': '10200827',
    'population_man': '5061809',
    'population_female': '5139018',
    'houshol': '4097562'},
   {'wrttimeid': '2008',
    'seq': '3',
    'regi': '부산',
    'population_tot': '3564577',
    'population_man': '1773154',
    'population_female': '1791423',
    'houshol': '1311724'},
   {'wrttimeid': '2008',
    'seq': '4',
    'regi': '대구',
    'population_tot': '2492724',
    'population_man': '1246873',
    'population_female': '1245851',
    'houshol': '894969'},
   {'wrttimeid': '2008',
    'seq': '5',
    'regi': '인천',
    'population_tot': '2692696',
    'population_man': '1356473',
    'population_female': '1336223',
    'houshol': '1014755'},
   {'wrttimeid': '2008',
    'seq': '6',
    'regi': '광주',
    'population_tot': '1422702',
    'population_man': '705817',
    'population_female': '716885',
    'houshol': '513021'},
   {'wrttimeid': '2008',
    'seq': '7',
    'regi': '대전',
    'population_tot': '1480895',
    'population_man': '741611',
    'population_female': '739284',
    'houshol': '531682'},
   {'wrttimeid': '2008',
    'seq': '8',
    'regi': '울산',
    'population_tot': '1112407',
    'population_man': '572815',
    'population_female': '539592',
    'houshol': '389735'},
   {'wrttimeid': '2008',
    'seq': '9',
    'regi': '경기',
    'population_tot': '11292264',
    'population_man': '5690673',
    'population_female': '5601591',
    'houshol': '4284475'},
   {'wrttimeid': '2008',
    'seq': '10',
    'regi': '강원',
    'population_tot': '1508575',
    'population_man': '759282',
    'population_female': '749293',
    'houshol': '606950'},
   {'wrttimeid': '2008',
    'seq': '11',
    'regi': '충북',
    'population_tot': '1519587',
    'population_man': '765398',
    'population_female': '754189',
    'houshol': '587411'},
   {'wrttimeid': '2008',
    'seq': '12',
    'regi': '충남',
    'population_tot': '2018537',
    'population_man': '1020317',
    'population_female': '998220',
    'houshol': '812871'},
   {'wrttimeid': '2008',
    'seq': '13',
    'regi': '전북',
    'population_tot': '1855772',
    'population_man': '924770',
    'population_female': '931002',
    'houshol': '710550'},
   {'wrttimeid': '2008',
    'seq': '14',
    'regi': '전남',
    'population_tot': '1919000',
    'population_man': '958491',
    'population_female': '960509',
    'houshol': '773087'},
   {'wrttimeid': '2008',
    'seq': '15',
    'regi': '경북',
    'population_tot': '2673931',
    'population_man': '1343199',
    'population_female': '1330732',
    'houshol': '1058099'},
   {'wrttimeid': '2008',
    'seq': '16',
    'regi': '경남',
    'population_tot': '3225255',
    'population_man': '1622127',
    'population_female': '1603128',
    'houshol': '1203767'},
   {'wrttimeid': '2008',
    'seq': '17',
    'regi': '제주',
    'population_tot': '560618',
    'population_man': '280088',
    'population_female': '280530',
    'houshol': '214681'},
   {'wrttimeid': '2009',
    'seq': '1',
    'regi': '계',
    'population_tot': '49773145',
    'population_man': '24929939',
    'population_female': '24843206',
    'houshol': '19261292'},
   {'wrttimeid': '2009',
    'seq': '2',
    'regi': '서울',
    'population_tot': '10208302',
    'population_man': '5059269',
    'population_female': '5149033',
    'houshol': '4116660'},
   {'wrttimeid': '2009',
    'seq': '3',
    'regi': '부산',
    'population_tot': '3543030',
    'population_man': '1761202',
    'population_female': '1781828',
    'houshol': '1323771'},
   {'wrttimeid': '2009',
    'seq': '4',
    'regi': '대구',
    'population_tot': '2489781',
    'population_man': '1243878',
    'population_female': '1245903',
    'houshol': '906470'},
   {'wrttimeid': '2009',
    'seq': '5',
    'regi': '인천',
    'population_tot': '2710579',
    'population_man': '1364809',
    'population_female': '1345770',
    'houshol': '1026936'},
   {'wrttimeid': '2009',
    'seq': '6',
    'regi': '광주',
    'population_tot': '1433640',
    'population_man': '711091',
    'population_female': '722549',
    'houshol': '524093'},
   {'wrttimeid': '2009',
    'seq': '7',
    'regi': '대전',
    'population_tot': '1484180',
    'population_man': '743121',
    'population_female': '741059',
    'houshol': '538100'},
   {'wrttimeid': '2009',
    'seq': '8',
    'regi': '울산',
    'population_tot': '1114866',
    'population_man': '573607',
    'population_female': '541259',
    'houshol': '394364'},
   {'wrttimeid': '2009',
    'seq': '9',
    'regi': '경기',
    'population_tot': '11460610',
    'population_man': '5773569',
    'population_female': '5687041',
    'houshol': '4359467'},
   {'wrttimeid': '2009',
    'seq': '10',
    'regi': '강원',
    'population_tot': '1512870',
    'population_man': '761270',
    'population_female': '751600',
    'houshol': '617693'},
   {'wrttimeid': '2009',
    'seq': '11',
    'regi': '충북',
    'population_tot': '1527478',
    'population_man': '769968',
    'population_female': '757510',
    'houshol': '599204'},
   {'wrttimeid': '2009',
    'seq': '12',
    'regi': '충남',
    'population_tot': '2037582',
    'population_man': '1029725',
    'population_female': '1007857',
    'houshol': '827846'},
   {'wrttimeid': '2009',
    'seq': '13',
    'regi': '전북',
    'population_tot': '1854508',
    'population_man': '924480',
    'population_female': '930028',
    'houshol': '720993'},
   {'wrttimeid': '2009',
    'seq': '14',
    'regi': '전남',
    'population_tot': '1913004',
    'population_man': '955954',
    'population_female': '957050',
    'houshol': '783156'},
   {'wrttimeid': '2009',
    'seq': '15',
    'regi': '경북',
    'population_tot': '2669876',
    'population_man': '1340977',
    'population_female': '1328899',
    'houshol': '1073367'},
   {'wrttimeid': '2009',
    'seq': '16',
    'regi': '경남',
    'population_tot': '3250176',
    'population_man': '1635700',
    'population_female': '1614476',
    'houshol': '1231461'},
   {'wrttimeid': '2009',
    'seq': '17',
    'regi': '제주',
    'population_tot': '562663',
    'population_man': '281319',
    'population_female': '281344',
    'houshol': '217711'},
   {'wrttimeid': '2010',
    'seq': '1',
    'regi': '계',
    'population_tot': '50515666',
    'population_man': '25310385',
    'population_female': '25205281',
    'houshol': '19865179'},
   {'wrttimeid': '2010',
    'seq': '2',
    'regi': '서울',
    'population_tot': '10312545',
    'population_man': '5111259',
    'population_female': '5201286',
    'houshol': '4224181'},
   {'wrttimeid': '2010',
    'seq': '3',
    'regi': '부산',
    'population_tot': '3567910',
    'population_man': '1773170',
    'population_female': '1794740',
    'houshol': '1371346'},
   {'wrttimeid': '2010',
    'seq': '4',
    'regi': '대구',
    'population_tot': '2511676',
    'population_man': '1255245',
    'population_female': '1256431',
    'houshol': '934598'},
   {'wrttimeid': '2010',
    'seq': '5',
    'regi': '인천',
    'population_tot': '2758296',
    'population_man': '1390356',
    'population_female': '1367940',
    'houshol': '1059664'},
   {'wrttimeid': '2010',
    'seq': '6',
    'regi': '광주',
    'population_tot': '1454636',
    'population_man': '721780',
    'population_female': '732856',
    'houshol': '540875'},
   {'wrttimeid': '2010',
    'seq': '7',
    'regi': '대전',
    'population_tot': '1503664',
    'population_man': '753648',
    'population_female': '750016',
    'houshol': '555768'},
   {'wrttimeid': '2010',
    'seq': '8',
    'regi': '울산',
    'population_tot': '1126298',
    'population_man': '579071',
    'population_female': '547227',
    'houshol': '405501'},
   {'wrttimeid': '2010',
    'seq': '9',
    'regi': '경기',
    'population_tot': '11786622',
    'population_man': '5942454',
    'population_female': '5844168',
    'houshol': '4527282'},
   {'wrttimeid': '2010',
    'seq': '10',
    'regi': '강원',
    'population_tot': '1529818',
    'population_man': '769807',
    'population_female': '760011',
    'houshol': '639001'},
   {'wrttimeid': '2010',
    'seq': '11',
    'regi': '충북',
    'population_tot': '1549528',
    'population_man': '781301',
    'population_female': '768227',
    'houshol': '617431'},
   {'wrttimeid': '2010',
    'seq': '12',
    'regi': '충남',
    'population_tot': '2075514',
    'population_man': '1049363',
    'population_female': '1026151',
    'houshol': '854432'},
   {'wrttimeid': '2010',
    'seq': '13',
    'regi': '전북',
    'population_tot': '1868963',
    'population_man': '931481',
    'population_female': '937482',
    'houshol': '740650'},
   {'wrttimeid': '2010',
    'seq': '14',
    'regi': '전남',
    'population_tot': '1918485',
    'population_man': '958624',
    'population_female': '959861',
    'houshol': '799520'},
   {'wrttimeid': '2010',
    'seq': '15',
    'regi': '경북',
    'population_tot': '2689920',
    'population_man': '1351202',
    'population_female': '1338718',
    'houshol': '1101486'},
   {'wrttimeid': '2010',
    'seq': '16',
    'regi': '경남',
    'population_tot': '3290536',
    'population_man': '1656042',
    'population_female': '1634494',
    'houshol': '1268731'}]}}

In [33]:
from pprint import pprint

In [34]:
pprint(data)

{'RegistrationPopulationByRegion': {'head': {'RESULT': {'resultCode': 'INFO-0',
                                                        'resultMsg': 'NOMAL '
                                                                     'SERVICE'},
                                             'numOfRows': '50',
                                             'pageNo': '1',
                                             'totalCount': '266',
                                             'type': 'XML'},
                                    'row': [{'houshol': '19005339',
                                             'population_female': '24717470',
                                             'population_man': '24822897',
                                             'population_tot': '49540367',
                                             'regi': '계',
                                             'seq': '1',
                                             'wrttimeid': '2008'},
                                            {'houshol': '4097562',
                                             'population_female': '5139018',
                                             'population_man': '5061809',
                                             'population_tot': '10200827',
                                             'regi': '서울',
                                             'seq': '2',
                                             'wrttimeid': '2008'},
                                            {'houshol': '1311724',
                                             'population_female': '1791423',
                                             'population_man': '1773154',
                                             'population_tot': '3564577',
                                             'regi': '부산',
                                             'seq': '3',
                                             'wrttimeid': '2008'},
                                            {'houshol': '894969',
                                             'population_female': '1245851',
                                             'population_man': '1246873',
                                             'population_tot': '2492724',
                                             'regi': '대구',
                                             'seq': '4',
                                             'wrttimeid': '2008'},
                                            {'houshol': '1014755',
                                             'population_female': '1336223',
                                             'population_man': '1356473',
                                             'population_tot': '2692696',
                                             'regi': '인천',
                                             'seq': '5',
                                             'wrttimeid': '2008'},
                                            {'houshol': '513021',
                                             'population_female': '716885',
                                             'population_man': '705817',
                                             'population_tot': '1422702',
                                             'regi': '광주',
                                             'seq': '6',
                                             'wrttimeid': '2008'},
                                            {'houshol': '531682',
                                             'population_female': '739284',
                                             'population_man': '741611',
                                             'population_tot': '1480895',
                                             'regi': '대전',
                                             'seq': '7',
                                             'wrttimeid': '2008'},
                                            {'houshol': '389735',
                                             'population_female': '539592',
                                             'population_man': '572815',
                                             'population_tot': '1112407',
                                             'regi': '울산',
                                             'seq': '8',
                                             'wrttimeid': '2008'},
                                            {'houshol': '4284475',
                                             'population_female': '5601591',
                                             'population_man': '5690673',
                                             'population_tot': '11292264',
                                             'regi': '경기',
                                             'seq': '9',
                                             'wrttimeid': '2008'},
                                            {'houshol': '606950',
                                             'population_female': '749293',
                                             'population_man': '759282',
                                             'population_tot': '1508575',
                                             'regi': '강원',
                                             'seq': '10',
                                             'wrttimeid': '2008'},
                                            {'houshol': '587411',
                                             'population_female': '754189',
                                             'population_man': '765398',
                                             'population_tot': '1519587',
                                             'regi': '충북',
                                             'seq': '11',
                                             'wrttimeid': '2008'},
                                            {'houshol': '812871',
                                             'population_female': '998220',
                                             'population_man': '1020317',
                                             'population_tot': '2018537',
                                             'regi': '충남',
                                             'seq': '12',
                                             'wrttimeid': '2008'},
                                            {'houshol': '710550',
                                             'population_female': '931002',
                                             'population_man': '924770',
                                             'population_tot': '1855772',
                                             'regi': '전북',
                                             'seq': '13',
                                             'wrttimeid': '2008'},
                                            {'houshol': '773087',
                                             'population_female': '960509',
                                             'population_man': '958491',
                                             'population_tot': '1919000',
                                             'regi': '전남',
                                             'seq': '14',
                                             'wrttimeid': '2008'},
                                            {'houshol': '1058099',
                                             'population_female': '1330732',
                                             'population_man': '1343199',
                                             'population_tot': '2673931',
                                             'regi': '경북',
                                             'seq': '15',
                                             'wrttimeid': '2008'},
                                            {'houshol': '1203767',
                                             'population_female': '1603128',
                                             'population_man': '1622127',
                                             'population_tot': '3225255',
                                             'regi': '경남',
                                             'seq': '16',
                                             'wrttimeid': '2008'},
                                            {'houshol': '214681',
                                             'population_female': '280530',
                                             'population_man': '280088',
                                             'population_tot': '560618',
                                             'regi': '제주',
                                             'seq': '17',
                                             'wrttimeid': '2008'},
                                            {'houshol': '19261292',
                                             'population_female': '24843206',
                                             'population_man': '24929939',
                                             'population_tot': '49773145',
                                             'regi': '계',
                                             'seq': '1',
                                             'wrttimeid': '2009'},
                                            {'houshol': '4116660',
                                             'population_female': '5149033',
                                             'population_man': '5059269',
                                             'population_tot': '10208302',
                                             'regi': '서울',
                                             'seq': '2',
                                             'wrttimeid': '2009'},
                                            {'houshol': '1323771',
                                             'population_female': '1781828',
                                             'population_man': '1761202',
                                             'population_tot': '3543030',
                                             'regi': '부산',
                                             'seq': '3',
                                             'wrttimeid': '2009'},
                                            {'houshol': '906470',
                                             'population_female': '1245903',
                                             'population_man': '1243878',
                                             'population_tot': '2489781',
                                             'regi': '대구',
                                             'seq': '4',
                                             'wrttimeid': '2009'},
                                            {'houshol': '1026936',
                                             'population_female': '1345770',
                                             'population_man': '1364809',
                                             'population_tot': '2710579',
                                             'regi': '인천',
                                             'seq': '5',
                                             'wrttimeid': '2009'},
                                            {'houshol': '524093',
                                             'population_female': '722549',
                                             'population_man': '711091',
                                             'population_tot': '1433640',
                                             'regi': '광주',
                                             'seq': '6',
                                             'wrttimeid': '2009'},
                                            {'houshol': '538100',
                                             'population_female': '741059',
                                             'population_man': '743121',
                                             'population_tot': '1484180',
                                             'regi': '대전',
                                             'seq': '7',
                                             'wrttimeid': '2009'},
                                            {'houshol': '394364',
                                             'population_female': '541259',
                                             'population_man': '573607',
                                             'population_tot': '1114866',
                                             'regi': '울산',
                                             'seq': '8',
                                             'wrttimeid': '2009'},
                                            {'houshol': '4359467',
                                             'population_female': '5687041',
                                             'population_man': '5773569',
                                             'population_tot': '11460610',
                                             'regi': '경기',
                                             'seq': '9',
                                             'wrttimeid': '2009'},
                                            {'houshol': '617693',
                                             'population_female': '751600',
                                             'population_man': '761270',
                                             'population_tot': '1512870',
                                             'regi': '강원',
                                             'seq': '10',
                                             'wrttimeid': '2009'},
                                            {'houshol': '599204',
                                             'population_female': '757510',
                                             'population_man': '769968',
                                             'population_tot': '1527478',
                                             'regi': '충북',
                                             'seq': '11',
                                             'wrttimeid': '2009'},
                                            {'houshol': '827846',
                                             'population_female': '1007857',
                                             'population_man': '1029725',
                                             'population_tot': '2037582',
                                             'regi': '충남',
                                             'seq': '12',
                                             'wrttimeid': '2009'},
                                            {'houshol': '720993',
                                             'population_female': '930028',
                                             'population_man': '924480',
                                             'population_tot': '1854508',
                                             'regi': '전북',
                                             'seq': '13',
                                             'wrttimeid': '2009'},
                                            {'houshol': '783156',
                                             'population_female': '957050',
                                             'population_man': '955954',
                                             'population_tot': '1913004',
                                             'regi': '전남',
                                             'seq': '14',
                                             'wrttimeid': '2009'},
                                            {'houshol': '1073367',
                                             'population_female': '1328899',
                                             'population_man': '1340977',
                                             'population_tot': '2669876',
                                             'regi': '경북',
                                             'seq': '15',
                                             'wrttimeid': '2009'},
                                            {'houshol': '1231461',
                                             'population_female': '1614476',
                                             'population_man': '1635700',
                                             'population_tot': '3250176',
                                             'regi': '경남',
                                             'seq': '16',
                                             'wrttimeid': '2009'},
                                            {'houshol': '217711',
                                             'population_female': '281344',
                                             'population_man': '281319',
                                             'population_tot': '562663',
                                             'regi': '제주',
                                             'seq': '17',
                                             'wrttimeid': '2009'},
                                            {'houshol': '19865179',
                                             'population_female': '25205281',
                                             'population_man': '25310385',
                                             'population_tot': '50515666',
                                             'regi': '계',
                                             'seq': '1',
                                             'wrttimeid': '2010'},
                                            {'houshol': '4224181',
                                             'population_female': '5201286',
                                             'population_man': '5111259',
                                             'population_tot': '10312545',
                                             'regi': '서울',
                                             'seq': '2',
                                             'wrttimeid': '2010'},
                                            {'houshol': '1371346',
                                             'population_female': '1794740',
                                             'population_man': '1773170',
                                             'population_tot': '3567910',
                                             'regi': '부산',
                                             'seq': '3',
                                             'wrttimeid': '2010'},
                                            {'houshol': '934598',
                                             'population_female': '1256431',
                                             'population_man': '1255245',
                                             'population_tot': '2511676',
                                             'regi': '대구',
                                             'seq': '4',
                                             'wrttimeid': '2010'},
                                            {'houshol': '1059664',
                                             'population_female': '1367940',
                                             'population_man': '1390356',
                                             'population_tot': '2758296',
                                             'regi': '인천',
                                             'seq': '5',
                                             'wrttimeid': '2010'},
                                            {'houshol': '540875',
                                             'population_female': '732856',
                                             'population_man': '721780',
                                             'population_tot': '1454636',
                                             'regi': '광주',
                                             'seq': '6',
                                             'wrttimeid': '2010'},
                                            {'houshol': '555768',
                                             'population_female': '750016',
                                             'population_man': '753648',
                                             'population_tot': '1503664',
                                             'regi': '대전',
                                             'seq': '7',
                                             'wrttimeid': '2010'},
                                            {'houshol': '405501',

In [35]:
data2 = data['RegistrationPopulationByRegion']['row']

In [39]:
import pandas as pd

In [40]:
df = pd.DataFrame(data2)

In [41]:
df

,wrttimeid,seq,regi,population_tot,population_man,population_female,houshol
0,2008,1,계,49540367,24822897,24717470,19005339
1,2008,2,서울,10200827,5061809,5139018,4097562
2,2008,3,부산,3564577,1773154,1791423,1311724
3,2008,4,대구,2492724,1246873,1245851,894969
4,2008,5,인천,2692696,1356473,1336223,1014755
5,2008,6,광주,1422702,705817,716885,513021
6,2008,7,대전,1480895,741611,739284,531682
7,2008,8,울산,1112407,572815,539592,389735
8,2008,9,경기,11292264,5690673,5601591,4284475
9,2008,10,강원,1508575,759282,749293,606950
10,2008,11,충북,1519587,765398,754189,587411
11,2008,12,충남,2018537,1020317,998220,812871
12,2008,13,전북,1855772,924770,931002,710550
13,2008,14,전남,1919000,958491,960509,773087
14,2008,15,경북,2673931,1343199,1330732,1058099
15,2008,16,경남,3225255,1622127,1603128,1203767
16,2008,17,제주,560618,280088,280530,214681
17,2009,1,계,49773145,24929939,24843206,19261292
18,2009,2,서울,10208302,5059269,5149033,4116660
19,2009,3,부산,3543030,1761202,1781828,1323771
20,2009,4,대구,2489781,1243878,1245903,906470
21,2009,5,인천,2710579,1364809,1345770,1026936
22,2009,6,광주,1433640,711091,722549,524093
23,2009,7,대전,1484180,743121,741059,538100
24,2009,8,울산,1114866,573607,541259,394364
25,2009,9,경기,11460610,5773569,5687041,4359467
26,2009,10,강원,1512870,761270,751600,617693
27,2009,11,충북,1527478,769968,757510,599204
28,2009,12,충남,2037582,1029725,1007857,827846
29,2009,13,전북,1854508,924480,930028,720993
30,2009,14,전남,1913004,955954,957050,783156
31,2009,15,경북,2669876,1340977,1328899,1073367
32,2009,16,경남,3250176,1635700,1614476,1231461
33,2009,17,제주,562663,281319,281344,217711
34,2010,1,계,50515666,25310385,25205281,19865179
35,2010,2,서울,10312545,5111259,5201286,4224181
36,2010,3,부산,3567910,1773170,1794740,1371346
37,2010,4,대구,2511676,1255245,1256431,934598
38,2010,5,인천,2758296,1390356,1367940,1059664
39,2010,6,광주,1454636,721780,732856,540875
40,2010,7,대전,1503664,753648,750016,555768
41,2010,8,울산,1126298,579071,547227,405501
42,2010,9,경기,11786622,5942454,5844168,4527282
43,2010,10,강원,1529818,769807,760011,639001
44,2010,11,충북,1549528,781301,768227,617431
45,2010,12,충남,2075514,1049363,1026151,854432
46,2010,13,전북,1868963,931481,937482,740650
47,2010,14,전남,1918485,958624,959861,799520
48,2010,15,경북,2689920,1351202,1338718,1101486
49,2010,16,경남,3290536,1656042,1634494,1268731

In [46]:
df.to_csv('test.csv')